name: Deploy to Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Use the version supported by AWS Lambda

      - name: Install dependencies and build
        run: |
          npm install
          npm prune --production
          zip -r deploy.zip ./*

      - name: Deploy Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name dev-MyLambdaFunction \
            --zip-file fileb://deploy.zip

