name: Deploy

on:
  push:
    branches:
    - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install NPM dependencies and build
        env:
          CI: true
        run: |
          npm install
          npm install -g @zeit/ncc # Install ncc globally
          ncc build index.js
          zip -j deploy.zip ./dist/*
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Deploy Lambda Function
        run: |
          aws lambda update-function-code --function-name=dev-MyLambdaFunction --zip-file=fileb://deploy.zip
